baseURL = "https://usmankhwaja.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Usman Khwaja"
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
enableGitInfo = true
disableHugoGeneratorInject = true
pluralizelisttitles = false
theme = "palemoss"
summaryLength = 20
disableKinds = ["section"]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

[taxonomies]
  category = "categories"

[params]
  description = "Front end engineer & Jamstack developer"
  images = ["https://pbs.twimg.com/profile_images/955102212539191301/-FeTpTi6_400x400.jpg"]
  keywords = ["web", "developer", "jamstack", "font-end", "websites", "blog", "personal", "portfolio", "coding", "software", "frontend"]
  github = "ukhwaja"

[permalinks]
  posts = "/:title/"