[build]
    publish = "public"
    command = "hugo"

[build.environment]
    HUGO_VERSION = "0.133.1"
    NODE_VERSION = "22.7.0"
    YARN_VERSION = "4.2.2"
    
# [[redirects]]
#     from = "https://usmankhwaja.netlify.com/*"
#     to = "https://usmankhwaja.com/:splat"
#     status = 301
#     force = true

# [[redirects]]
#     from = "https://usmankhwaja.netlify.app/*"
#     to = "https://usmankhwaja.com/:splat"
#     status = 301
#     force = true

[[headers]]
    for = "/*"
    [headers.values]
        Link = "<https://cdn.ampproject.org/v0.js>; rel=preload; as=script, <https://fonts.gstatic.com/>; rel=preconnect"

[[headers]]
    for = "/digital-footprint"
    [headers.values]
        Link = "<https://cdn.ampproject.org/v0.js>; rel=preload; as=script, <https://fonts.gstatic.com/>; rel=preconnect, <https://img.icons8.com/>; rel=preconnect"
